spring:
  application.name: "URL Shortener"

  datasource:
    url: jdbc:h2:mem:memDb
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:h2:file:./h2db-url-shortener;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  h2:
    console:
      enabled: false
